version: "3.7"
services:

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
    networks:
      - backend
    volumes:
      - ~/ipfs/ipfs:/data/ipfs

  ipfs_cluster:
    image: ipfs/ipfs-cluster:latest
    ports:
      - "9094:9094"
      - "9095:9094"
      - "9096:9096"
    volumes:
      - ~/ipfs/ipfs-cluster:/data/ipfs-cluster
    networks:
      - backend
    depends_on:
      - ipfs
    environment:
      - CLUSTER_IPFSHTTP_NODEMULTIADDRESS=/dns4/ipfs/tcp/5001
      - CLUSTER_IPFSPROXY_NODEMULTIADDRESS=/dns4/ipfs/tcp/5001

  networks:
    backend: